import type { Metadata } from 'next';
import './globals.css';
import MainHeader from '@/components/custom/main-header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='dark max-w-screen-lg mx-auto px-8'>
        <MainHeader />
        {children}
      </body>
    </html>
  );
}
